global:
  scrape_interval: 5m
  evaluation_interval: 5m

remote_write:
  - url: http://localhost:9009/api/v1/push
    write_relabel_configs:
      - source_labels: [__name__]
        regex: (^rpc_.*|substrate_rpc_calls_started)
        action: keep

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: "rpc-mon"
    metrics_path: "/"
    static_configs:
      - targets: ["mon-eu-central.rpc-providers.net:80"]
      - targets: ["mon-us-east.rpc-providers.net:80"]
      - targets: ["mon-ap-southeast.rpc-providers.net:80"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "stakeworld"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="stakeworld", __name__=~".*substrate_rpc_calls_sta.*"}'
    static_configs:
      - targets:
        - monitor.stakeworld.io:9091
  - job_name: "GlobalStake"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="GlobalStake", __name__=~".*substrate_rpc_calls_sta.*"}'
    static_configs:
      - targets:
        - '216.66.9.45:9090'
  - job_name: "Helixstreet"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="Helixstreet", __name__=~".*substrate_rpc_calls_sta.*"}'
    static_configs:
      - targets:
        - 'rpc-prometheus.helixstreet.io:9090'
  - job_name: "Dwellir"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="Dwellir", __name__=~".*substrate_rpc_calls_sta.*"}'
    scheme: https
    tls_config:
            insecure_skip_verify: true
    static_configs:
      - targets: ['rpc-monitoring.dwellir.com']
  - job_name: "RadiumBlock"
    scrape_interval: 15s
    honor_labels: true
    static_configs:
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /polkadot
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /bridgehub-polkadot
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /kusama
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /statemine
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /statemint
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /bridgehub-kusama
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /collectives
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /people-polkadot
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /people-kusama
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /coretime-polkadot
      - targets:
        - "polkadot-public-rpc.prometheus.radiumblock.co:80"   
        labels:
          __metrics_path__: /westend    
  # onfinality
  - job_name: "onfinality"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    params:
      "match[]":
        - '{job="onfinality", __name__=~".*substrate_rpc_calls_sta.*"}'
    static_configs:
      - targets: ['rpc-prometheus-eu.onfinality.io']
      - targets: ['rpc-prometheus-hm.onfinality.io']
      - targets: ['rpc-prometheus-nv.onfinality.io']
  # simplystaking
  - job_name: "Simply Staking"
    scrape_interval: 15s
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="Simply Staking", __name__=~".*substrate_rpc_calls_sta.*"}'
    static_configs:
      - targets: ['50.21.167.187:9090']
